"""Shared plumbing for the characterization goldens (isfinder-annotation 01).

Two tiers of golden, both living under ``tests/goldens/``:

* **Parser-level** -- ``tests/fixtures/isfinder/blast.out`` through
  ``ijump isfinder-db-parse``. Inputs and outputs are a few kilobytes, so both
  are committed; the tier needs only BLAST+ on PATH, which clustering's
  all-vs-all search runs.
* **End-to-end** -- both estimation modes over the sample alignment. The
  alignment is 840 MB and cannot be committed, so the *outputs* are committed
  and the *inputs* are looked up on disk; when they are not there the tests
  skip.

Both the tests and ``tests/regenerate_goldens.py`` invoke iJump through this
module, so a golden is regenerated by exactly the command the test compares
against.
"""

import os
import shutil
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
GOLDENS_DIR = Path(__file__).resolve().parent / "goldens"
FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"

# --- parser-level tier ------------------------------------------------------

# A byte-identical copy of Test/blast.out (gitignored, hence the copy): the
# ISFinder BLAST outfmt-6 run of Test/A_baumannii_assembly.fna against a clone
# of the ISFinder database.
ISFINDER_BLAST_OUT = FIXTURES_DIR / "isfinder" / "blast.out"

# The reference the search above was run against, with everything outside a
# called locus masked to N -- see make_reference_fixture.py beside it. Clustering
# reads the loci out of the reference, and the real 4 MB assembly is gitignored.
ISFINDER_REFERENCE = FIXTURES_DIR / "isfinder" / "reference.fna.gz"

ISFINDER_GOLDEN_DIR = GOLDENS_DIR / "isfinder_db_parse"
ISFINDER_TABLE_NAME = "ISTable_processing.txt"


def missing_parser_requirements():
    """Reasons the parser-level golden cannot run here, as a list of strings.

    Only one: clustering runs an all-vs-all ``blastn`` over the called loci, so
    the tier needs BLAST+ even though its inputs are committed.
    """
    return [
        f"{tool} not on PATH" for tool in ("blastn", "makeblastdb") if shutil.which(tool) is None
    ]


def run_isfinder_db_parse(outdir, reference=None, extra_args=()):
    """Parse the committed ISFinder BLAST output into an IS table in ``outdir``.

    ``reference`` and ``extra_args`` are for tests that vary one input -- the
    golden itself passes neither, so it is always the same command.
    """
    return subprocess.run(
        [
            "ijump",
            "isfinder-db-parse",
            "-b",
            str(ISFINDER_BLAST_OUT),
            "-r",
            str(reference if reference is not None else ISFINDER_REFERENCE),
            "-o",
            str(outdir),
            *extra_args,
        ],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )


# --- end-to-end tier --------------------------------------------------------

# Directory holding the large inputs. Overridable so the goldens can be run
# against a copy of Test/ that lives outside the repo.
E2E_DATA_ENV_VAR = "IJUMP_E2E_DATA"
E2E_DATA_DEFAULT = REPO_ROOT / "Test"

E2E_INPUTS = {
    "aln": "Sample.bam",
    "ref": "A_baumannii_assembly.fna",
    "gff": "Acinetobacter_baumannii_ATCC17978.gff",
}

# The IS table the end-to-end run consumes is the *parser tier's own golden*, not
# a copy sitting in the data directory. That chains the two tiers: when a later
# ticket changes the parser's output on purpose and the parser golden is re-pinned,
# the end-to-end tier picks the new table up instead of silently going on
# consuming a stale one.
E2E_IS_TABLE = ISFINDER_GOLDEN_DIR / ISFINDER_TABLE_NAME

E2E_GOLDEN_DIR = GOLDENS_DIR / "e2e"

# Files pinned per mode, as <relative path under the golden dir> -> <relative
# path under the run directory>. ``reads.txt`` is deliberately not pinned: it is
# a 900 KB dump of every clipped read, not a report table, and none of the
# tickets in this series change it.
E2E_GOLDEN_FILES = {
    "average": {
        "report/ijump_junctions.txt": "out/ijump_junctions.txt",
        "report/ijump_sum_by_reg.txt": "out/ijump_sum_by_reg.txt",
        "report/ijump_report_by_is_reg.txt": "out/ijump_report_by_is_reg.txt",
    },
    # Precise mode writes no per-region tables; its report table is the
    # junction pairs.
    "precise": {
        "report/ijump_junctions.txt": "out/ijump_junctions.txt",
        "report/ijump_junction_pairs.txt": "out/ijump_junction_pairs.txt",
    },
}

E2E_MODES = tuple(E2E_GOLDEN_FILES)


def e2e_data_dir():
    """Directory the large end-to-end inputs are read from."""
    override = os.environ.get(E2E_DATA_ENV_VAR)
    return Path(override) if override else E2E_DATA_DEFAULT


def missing_e2e_requirements():
    """Reasons the end-to-end goldens cannot run here, as a list of strings.

    Empty list means everything needed is present. Anything else is a skip
    reason, not a failure: absent large inputs are the expected state on any
    machine that is not the maintainer's.
    """
    reasons = []

    data_dir = e2e_data_dir()
    for filename in E2E_INPUTS.values():
        if not (data_dir / filename).is_file():
            reasons.append(f"missing input {data_dir / filename}")

    # pysam accepts any of these index spellings, so require only that one exists.
    aln = data_dir / E2E_INPUTS["aln"]
    index_candidates = [
        aln.with_suffix(".bam.bai"),
        aln.with_suffix(".bam.csi"),
        aln.with_suffix(".bai"),
        aln.with_suffix(".csi"),
    ]
    if aln.is_file() and not any(candidate.is_file() for candidate in index_candidates):
        reasons.append(f"no BAM index beside {aln}")

    for tool in ("blastn", "makeblastdb"):
        if shutil.which(tool) is None:
            reasons.append(f"{tool} not on PATH")

    return reasons


def run_e2e_pipeline(mode, run_dir, is_table_path=None):
    """Run one estimation mode over the large inputs inside ``run_dir``.

    ``is_table_path`` overrides the IS table the run consumes. The goldens pass
    nothing and get the parser tier's own golden, which is the chaining described
    above; a test checking that some *other* back-end's table drives a run passes
    its own (isfinder-annotation 09).

    The reference FASTA (and any BLAST database already built beside it) is
    copied into ``run_dir`` first, so a missing database is rebuilt there
    instead of in the shared input directory, and so nothing the run writes
    lands outside ``run_dir``.

    Returns the CompletedProcess.
    """
    data_dir = e2e_data_dir()
    run_dir = Path(run_dir)
    run_dir.mkdir(parents=True, exist_ok=True)

    ref_source = data_dir / E2E_INPUTS["ref"]
    for sibling in data_dir.glob(ref_source.stem + ".*"):
        shutil.copy2(sibling, run_dir / sibling.name)
    ref = run_dir / ref_source.name

    args = [
        "ijump",
        "run",
        "--aln",
        str(data_dir / E2E_INPUTS["aln"]),
        "--ref",
        str(ref),
        "--gff",
        str(data_dir / E2E_INPUTS["gff"]),
        "--isel",
        str(is_table_path if is_table_path is not None else E2E_IS_TABLE),
        "--outdir",
        str(run_dir / "out"),
        "--wd",
        str(run_dir / "wd"),
        "--estimation_mode",
        mode,
    ]

    return subprocess.run(args, cwd=run_dir, capture_output=True, text=True)
